version: 0.2
env:
  git-credential-helper: yes
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - n 18
      - npm install
  build:
    commands:
      - npm install -g serverless
      - serverless plugin install -n serverless-deployment-bucket
      - serverless package --region $Region --stage $Environment --param PipelineArtifactBucket=$PipelineArtifactBucket 
                                                                 --param SecretsmanagerArn=$SecretsmanagerArn
      - ls -al
artifacts:
  files:
    - '**/**'